### ISSUE TITLE
Set area and rows/cols with `grid-template-<name>` shorthand

### ISSUE THREAD

**Issue by c-harding** [SavvyWombat/tailwindcss-grid-areas#14]
# Feature request

**`grid-template-layout` should be a shorthand for `grid-areas-layout grid-cols-layout grid-rows-layout`**

If the same name is used for an area template, a column template and a row template (or just two of these), it is very likely they are meant to be used together. I propose a new shorthand: `grid-template-<name>`. This should assign all of the above.

## Generated CSS

It would probably make sense to generate separate CSS rules as follows:

```css
.grid-template-navbar {
  grid-template-areas: '...';
  grid-template-rows: '...';
}

.grid-template-layout {
  grid-template-areas: '...';
  grid-template-columns: '...';
  grid-template-rows: '...';
}

.grid-areas-navbar { grid-template-areas: '...' }
.grid-cols-navbar { grid-template-columns: '...' }
.grid-rows-navbar { grid-template-rows: '...' }

.grid-areas-layout { grid-template-areas: '...' }
.grid-cols-layout { grid-template-columns: '...' }
.grid-rows-layout { grid-template-rows: '...' }
```

Rather than adding two selectors to the same rule

```css
.grid-template-navbar, .grid-areas-navbar { grid-template-areas: '...' }
.grid-template-navbar, .grid-cols-navbar { grid-template-columns: '...' }
.grid-template-navbar, .grid-rows-navbar { grid-template-rows: '...' }

.grid-template-layout, .grid-areas-navbar { grid-template-areas: '...' }
.grid-template-layout, .grid-cols-navbar { grid-template-columns: '...' }
.grid-template-layout, .grid-rows-navbar { grid-template-rows: '...' }
```

This is for reasons of precedence: the classlist `grid-template-layout grid-cols-navbar` should override the template with the cols.
